import type { Task } from "./types";


export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Fix login bug',
    description: 'User cannot log in with correct credentials.',
    status: 'To Do',
    category: 'Bug',
    priority: 'High',
  },
  {
    id: '2',
    title: 'Add dark mode',
    description: 'Implement dark mode toggle in settings.',
    status: 'In Progress',
    category: 'Feature',
    priority: 'Medium',
  },
  {
    id: '3',
    title: 'Write README',
    description: 'Document setup steps for new devs.',
    status: 'Done',
    category: 'Documentation',
    priority: 'Low',
  },
  {
    id: '4',
    title: 'Refactor auth logic',
    description: 'Split auth logic into separate hooks.',
    status: 'To Do',
    category: 'Refactor',
    priority: 'Medium',
  },
  {
    id: '5',
    title: 'Add unit tests',
    description: 'Add tests for user reducer.',
    status: 'In Progress',
    category: 'Test',
    priority: 'High',
  },
  {
    id: '6',
    title: 'Fix sidebar overflow',
    description: 'Sidebar layout breaks on small screens.',
    status: 'To Do',
    category: 'Bug',
    priority: 'Low',
  },
  {
    id: '7',
    title: 'Update feature flags',
    description: 'Toggle new dashboard only for admins.',
    status: 'Done',
    category: 'Feature',
    priority: 'Medium',
  },
  {
    id: '8',
    title: 'Refactor theme provider',
    description: 'Simplify MUI theme logic and improve performance.',
    status: 'In Progress',
    category: 'Refactor',
    priority: 'Low',
  },
  {
    id: '9',
    title: 'Improve accessibility',
    description: 'Add ARIA labels to form fields.',
    status: 'To Do',
    category: 'Documentation',
    priority: 'Medium',
  },
  {
    id: '10',
    title: 'Fix build warnings',
    description: 'Clean up unused imports and types.',
    status: 'Done',
    category: 'Bug',
    priority: 'Low',
  },
]
